### ISSUE TITLE
Go Wiki

### ISSUE THREAD

**Issue by nathany** [rakyll/go-hardware#1]
Why not add this as a page on the Go wiki?

https://github.com/golang/go/wiki

**Comment by rakyll** [comment]
It might be a better fit for the Projects page, https://github.com/golang/go/wiki/Projects.

**Comment by nathany** [comment]
That would make sense. 
https://github.com/golang/go/wiki/Projects#hardware

Hopefully a little easier for people to find (or stumble upon).

**Comment by rakyll** [comment]
I added a link underneath the indexes subtitle at https://github.com/golang/go/wiki/Projects#indexes-and-search-engines.

> P.S. Thanks for putting together this list.

Thanks 😇

**Comment by nathany** [comment]
Cool.
