### ISSUE TITLE
Add go.hid?

### ISSUE THREAD

**Issue by GeertJohan** [rakyll/go-hardware#3]
Heya,

I made go.hid which wraps hidapi, it's used to communicate with USB Human Interface Devices.
github.com/GeertJohan/go.hid

Do you think this is hardware-y enough to be on the list?

**Comment by rakyll** [comment]
Yes, it is. Could you please open a pull request?

**Comment by GeertJohan** [comment]
Under which category should it go? Or a new one? "Communication protocols" or something like that?

**Comment by rakyll** [comment]
Maybe you can rename Networking to "Networking, communications".

**Comment by rakyll** [comment]
de70d49fa3d8ef210f5879eebd5a5daad890fab9 closed this issue.
